// Ambient declarations for untyped deps and generated build artifacts.

// b4a ships no TypeScript types (its react-native entry is plain JS).
declare module 'b4a'

// Generated by `npm run bundle-backend`: a CommonJS module exporting the base64 bundle.
declare module '*/app.bundle.js' {
  const base64: string
  export default base64
}
